version: '3.8'  # specify the version of Docker Compose file format
services:
  api:
    build:
      context: .  # Change this to the directory where your Dockerfile is located
      dockerfile: Dockerfile
    container_name: 'idrl-api'
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "80:5050"