version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-managemen
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'idrl-api'
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "80:5050"
networks:
  idrl-net:
    # configuration for idrl-net network
volumes:
  pgdata:
    # configuration for pgdata volume